# Generated by Django 6.0.1 on 2026-02-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_image', models.ImageField(upload_to='map/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
