# Generated by Django 6.0.1 on 2026-02-18 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_whychooseussection_whychooseusfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseussection',
            name='title',
        ),
        migrations.AddField(
            model_name='whychooseussection',
            name='heading',
            field=models.CharField(default='Why choose Us', max_length=100),
        ),
        migrations.AddField(
            model_name='whychooseussection',
            name='left_image',
            field=models.ImageField(default=0, upload_to='why_choose_left/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='why_choose_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.whychooseussection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='WhyChooseUsFeature',
        ),
    ]
