# Generated by Django 6.0.1 on 2026-02-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_whychooseussection_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('student_image', models.ImageField(upload_to='how_it_works/student/')),
            ],
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='how_it_works/icons/')),
                ('step_number', models.IntegerField()),
                ('card_bg_color', models.CharField(default='#F4D7A1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
