# Generated by Django 6.0.1 on 2026-02-19 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_successstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseussection',
            name='heading',
        ),
        migrations.AddField(
            model_name='whychooseussection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whychooseussection',
            name='title',
            field=models.CharField(default='Why Choose Us', max_length=200),
        ),
        migrations.AlterField(
            model_name='whychooseussection',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='why_choose_us/left_images/'),
        ),
        migrations.CreateModel(
            name='WhyChooseUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='why_choose_us/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='accounts.whychooseussection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='WhyChooseUsItem',
        ),
    ]
