# Generated by Django 6.0.1 on 2026-02-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_whychooseussection_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
