# Generated by Django 6.0.1 on 2026-02-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_footerlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemSectioned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('center_text', models.CharField(max_length=200)),
                ('left_image', models.ImageField(upload_to='eco/')),
            ],
        ),
        migrations.CreateModel(
            name='EcosystemItemed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='eco/logos/')),
                ('point1', models.CharField(max_length=255)),
                ('site_link', models.URLField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.ecosystemsectioned')),
            ],
        ),
    ]
