# Generated by Django 6.0.1 on 2026-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_ecosystemsectioned_ecosystemitemed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='career_men/')),
            ],
        ),
    ]
