# Generated by Django 6.0.1 on 2026-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_careermen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='success_story/')),
                ('video', models.FileField(blank=True, null=True, upload_to='success_stories_videos/')),
            ],
        ),
    ]
