# Generated by Django 6.0.1 on 2026-02-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_storyrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyrole',
            name='image',
        ),
        migrations.RemoveField(
            model_name='storyrole',
            name='video',
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='success_story/')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.storyrole')),
            ],
        ),
    ]
