# Generated by Django 6.0.1 on 2026-02-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Development', 'Development'), ('Design', 'Design'), ('Data', 'Data'), ('Emerging Tech', 'Emerging Tech')], max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('level', models.CharField(default='Beginner to Advanced', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='courses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
