# Generated by Django 6.0.1 on 2026-02-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_thumbnail', models.ImageField(upload_to='courses/video_thumbnails/')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='courses/technologies/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='courses.coursedetails')),
            ],
        ),
    ]
