# Generated by Django 6.0.1 on 2026-02-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('upi', 'UPI'), ('netbanking', 'Net Banking'), ('card', 'Card')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
