# Generated by Django 6.0.1 on 2026-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mission', 'Mission'), ('vision', 'Vision')], max_length=20)),
                ('icon', models.ImageField(upload_to='mission_vision/')),
            ],
        ),
    ]
