# Generated by Django 6.0.1 on 2026-02-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_ecosystemsection_ecosystemitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='value_icons/')),
                ('bullets', models.JSONField()),
            ],
        ),
    ]
