# Generated by Django 6.0.1 on 2026-02-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_valuecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='training_steps/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('journey_name', models.CharField(default='Your Training Journey', max_length=100)),
            ],
        ),
    ]
