# Generated by Django 6.0.1 on 2026-02-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_trainingstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoCanJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='who_can_join/')),
                ('color', models.CharField(choices=[('orange', 'Orange'), ('purple', 'Purple')], default='orange', max_length=10)),
            ],
        ),
    ]
