# Generated by Django 6.0.1 on 2026-02-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_whocanjoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='career_person/')),
            ],
        ),
    ]
